import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "codebyakib",
  // description: "Generated by create next app",
  title: 'codebyakib',
  description: 'My Portfolio Website',
  icons: {
    // icon: '/a-fav.png', 
    icon: '/c-fav-2.png',
    shortcut: '/a-fav.png',
    apple: '/a-fav.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


    <html lang="en">
      <head>
        <link rel="icon" />
      </head>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
        <Toaster position="top-right" reverseOrder={false} />

      </body>
    </html>
  );
}
